server:
  port: 8084
  servlet:
    context-path: /auth

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: auth
    password: auth
    url: jdbc:postgresql://localhost:5435/auth
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
    
  application:
    name: auth
